-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 22:48:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema scoadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema scoadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `scoadb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `scoadb` ;

-- -----------------------------------------------------
-- Table `scoadb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoadb`.`Pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(12) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `endereco` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_gej40f8jfd5efnwlggtpwjloo` (`cpf` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scoadb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoadb`.`Aluno` (
  `pessoa_id` INT(11) NOT NULL,
  PRIMARY KEY (`pessoa_id`),
  CONSTRAINT `FKdhmnlbjhg21llgs46ekorgswx`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `scoadb`.`Pessoa` (`id`)
	ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scoadb`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoadb`.`Disciplina` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(2555) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `scoadb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `scoadb`.`Professor` (
  `pessoa_id` INT(11) NOT NULL,
  PRIMARY KEY (`pessoa_id`),
  CONSTRAINT `FKhdx7tr0f98w7q50nwskcakga2`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `scoadb`.`Pessoa` (`id`)
	ON DELETE CASCADE)
	
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
